name: Code Quality

on:
  push:
    branches:
      - 'code-quality'
      - 'master'
  pull_request:
    branches:
      - 'code-quality'
      - 'master'

jobs:

  check:

    name: Quality Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy pytest pytest-cov
        pip install -e .
        pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Run pylint
      run: pylint --rcfile .pylintrc fdet
    - name: Run mypy
      run: mypy --config-file .mypy.ini fdet
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
